name: 'Cache'
on:
  push:
  repository_dispatch:
  schedule:
    - cron: '30 23 * * *'
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: |
        versions=$(curl -sSL https://getcomposer.org/versions)
        release_versions=$(curl -sSL https://github.com/shivammathur/composer-cache/releases/latest/download/versions)
        if [ "$versions" = "$release_versions" ]; then
          echo "No new releases"
        else
          for v in stable preview snapshot 1 2; do
            curl -o composer-$v.phar -sSL https://getcomposer.org$(echo $versions | jq -r ".\"$v\"[].path")
            php -r "try {\$p=new Phar('composer-$v.phar', 0);exit(0);} catch(Exception \$e) {exit(1);}"
            if [ $? -eq 1 ]; then
              echo "Could not download composer $v"
              exit 1;
            else
              sudo cp ./composer-$v.phar /usr/local/bin/composer
              sudo chmod a+x /usr/local/bin/composer
              release=$(composer -V)
              echo $release
            fi
          done
          curl -o versions -sSL https://getcomposer.org/versions
          set -x
          assets=()
          for asset in ./*.phar; do
            assets+=("$asset")
          done
          assets+=("./versions")
          echo "${assets[@]}"
          gh release delete "versions" -y || true
          gh release create "versions" "${assets[@]}"  -t "versions" -F ./versions
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
