name: 'Cache'
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      force:        
        type: choice
        description: Update phars by force
        options:
        - true
        - false
        default: 'false'
        required: false
  schedule:
    - cron: '0 * * * *'
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      run: bash cache.sh
      env:
        FORCE: ${{ github.event.inputs.force }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
